apiVersion: v1
kind: Service
metadata:
  name: ratings
spec:
  selector:
    app: ratings
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31000
  type: NodePort
  