apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'cadvisor'
        static_configs:
          - targets: ['cadvisor.default.svc.cluster.local:8080']
            
      - job_name: 'ratings'
        static_configs:
          - targets: ['ratings.default.svc.cluster.local:5000']

      - job_name: 'recommender'
        static_configs:
          - targets: ['recommender.default.svc.cluster.local:5001']
            
