apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'cadvisor'
        static_configs:
          - targets: ['cadvisor.default.svc.cluster.local:8080']

