apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender
  labels:
    app: recommender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommender
  template:
    metadata:
      labels:
        app: recommender
    spec:
      containers:
        - name: recommender
          image: fokaefs/recommender:instrumented-v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
              protocol: TCP
          env:
            - name: SERVICE_NAME
              value: recommender
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      